services:
  textgen:
    image: ${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - ./.env
      - ./../.env
    develop:
      watch:
        - path: .
          action: rebuild
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
